# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI_Files/DDLCreate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DDLCREATE(object):
    def setupUi(self, DDLCREATE):
        DDLCREATE.setObjectName("DDLCREATE")
        DDLCREATE.resize(838, 557)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DDLCREATE)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.create_dbname = QtWidgets.QTextEdit(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_dbname.sizePolicy().hasHeightForWidth())
        self.create_dbname.setSizePolicy(sizePolicy)
        self.create_dbname.setObjectName("create_dbname")
        self.horizontalLayout.addWidget(self.create_dbname)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(DDLCREATE)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(125, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.create_dbtable = QtWidgets.QTextEdit(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_dbtable.sizePolicy().hasHeightForWidth())
        self.create_dbtable.setSizePolicy(sizePolicy)
        self.create_dbtable.setObjectName("create_dbtable")
        self.horizontalLayout_8.addWidget(self.create_dbtable)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.create_createbutton = QtWidgets.QPushButton(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_createbutton.sizePolicy().hasHeightForWidth())
        self.create_createbutton.setSizePolicy(sizePolicy)
        self.create_createbutton.setObjectName("create_createbutton")
        self.horizontalLayout_7.addWidget(self.create_createbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.create_columnname = QtWidgets.QTextEdit(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_columnname.sizePolicy().hasHeightForWidth())
        self.create_columnname.setSizePolicy(sizePolicy)
        self.create_columnname.setObjectName("create_columnname")
        self.horizontalLayout_6.addWidget(self.create_columnname)
        spacerItem9 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_4 = QtWidgets.QLabel(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem11 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.create_datatype = QtWidgets.QComboBox(DDLCREATE)
        self.create_datatype.setObjectName("create_datatype")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.create_datatype.addItem("")
        self.horizontalLayout_5.addWidget(self.create_datatype)
        self.label_5 = QtWidgets.QLabel(DDLCREATE)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem12 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.label_6 = QtWidgets.QLabel(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem14 = QtWidgets.QSpacerItem(62, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.create_constraint = QtWidgets.QComboBox(DDLCREATE)
        self.create_constraint.setObjectName("create_constraint")
        self.create_constraint.addItem("")
        self.create_constraint.addItem("")
        self.create_constraint.addItem("")
        self.create_constraint.addItem("")
        self.create_constraint.addItem("")
        self.create_constraint.addItem("")
        self.create_constraint.addItem("")
        self.horizontalLayout_4.addWidget(self.create_constraint)
        self.label_7 = QtWidgets.QLabel(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem15 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_addbutton = QtWidgets.QPushButton(DDLCREATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_addbutton.sizePolicy().hasHeightForWidth())
        self.create_addbutton.setSizePolicy(sizePolicy)
        self.create_addbutton.setObjectName("create_addbutton")
        self.horizontalLayout_3.addWidget(self.create_addbutton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DDLCREATE)
        QtCore.QMetaObject.connectSlotsByName(DDLCREATE)

    def retranslateUi(self, DDLCREATE):
        _translate = QtCore.QCoreApplication.translate
        DDLCREATE.setWindowTitle(_translate("DDLCREATE", "Create"))
        self.label.setText(_translate("DDLCREATE", "Database Name:"))
        self.label_2.setText(_translate("DDLCREATE", "Table Name:"))
        self.create_createbutton.setText(_translate("DDLCREATE", "CREATE"))
        self.label_3.setText(_translate("DDLCREATE", "Column Name:"))
        self.label_4.setText(_translate("DDLCREATE", "Data Type:"))
        self.create_datatype.setItemText(0, _translate("DDLCREATE", "INT"))
        self.create_datatype.setItemText(1, _translate("DDLCREATE", "CHAR"))
        self.create_datatype.setItemText(2, _translate("DDLCREATE", "VARCHAR"))
        self.create_datatype.setItemText(3, _translate("DDLCREATE", "TEXT"))
        self.create_datatype.setItemText(4, _translate("DDLCREATE", "BLOB"))
        self.create_datatype.setItemText(5, _translate("DDLCREATE", "BOOLEAN"))
        self.create_datatype.setItemText(6, _translate("DDLCREATE", "TINYINT"))
        self.create_datatype.setItemText(7, _translate("DDLCREATE", "SMALLINT"))
        self.create_datatype.setItemText(8, _translate("DDLCREATE", "HUGEINT"))
        self.create_datatype.setItemText(9, _translate("DDLCREATE", "BIGINT"))
        self.create_datatype.setItemText(10, _translate("DDLCREATE", "DECIMAL"))
        self.create_datatype.setItemText(11, _translate("DDLCREATE", "REAL"))
        self.label_5.setText(_translate("DDLCREATE", "Hint: Integer/Char"))
        self.label_6.setText(_translate("DDLCREATE", "Constraint:"))
        self.create_constraint.setItemText(0, _translate("DDLCREATE", "PRIMARY KEY"))
        self.create_constraint.setItemText(1, _translate("DDLCREATE", "UNIQUE"))
        self.create_constraint.setItemText(2, _translate("DDLCREATE", "CHECK"))
        self.create_constraint.setItemText(3, _translate("DDLCREATE", "FOREIGN KEY"))
        self.create_constraint.setItemText(4, _translate("DDLCREATE", "NOT NULL"))
        self.create_constraint.setItemText(5, _translate("DDLCREATE", "DEFAULT"))
        self.create_constraint.setItemText(6, _translate("DDLCREATE", "INDEX"))
        self.label_7.setText(_translate("DDLCREATE", "Hint: Primary Key"))
        self.create_addbutton.setText(_translate("DDLCREATE", "ADD"))

