# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI_Files/DDLDrop.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DDLDROP(object):
    def setupUi(self, DDLDROP):
        DDLDROP.setObjectName("DDLDROP")
        DDLDROP.resize(838, 557)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DDLDROP)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(DDLDROP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.drop_dbname = QtWidgets.QTextEdit(DDLDROP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drop_dbname.sizePolicy().hasHeightForWidth())
        self.drop_dbname.setSizePolicy(sizePolicy)
        self.drop_dbname.setObjectName("drop_dbname")
        self.horizontalLayout.addWidget(self.drop_dbname)
        self.drop_listtablebutton = QtWidgets.QPushButton(DDLDROP)
        self.drop_listtablebutton.setObjectName("drop_listtablebutton")
        self.horizontalLayout.addWidget(self.drop_listtablebutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(DDLDROP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.drop_listview = QtWidgets.QListWidget(DDLDROP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drop_listview.sizePolicy().hasHeightForWidth())
        self.drop_listview.setSizePolicy(sizePolicy)
        self.drop_listview.setObjectName("drop_listview")
        self.horizontalLayout_2.addWidget(self.drop_listview)
        spacerItem4 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(DDLDROP)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(124, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.drop_dbtable = QtWidgets.QTextEdit(DDLDROP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drop_dbtable.sizePolicy().hasHeightForWidth())
        self.drop_dbtable.setSizePolicy(sizePolicy)
        self.drop_dbtable.setObjectName("drop_dbtable")
        self.horizontalLayout_8.addWidget(self.drop_dbtable)
        spacerItem7 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.drop_dropbutton = QtWidgets.QPushButton(DDLDROP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drop_dropbutton.sizePolicy().hasHeightForWidth())
        self.drop_dropbutton.setSizePolicy(sizePolicy)
        self.drop_dropbutton.setObjectName("drop_dropbutton")
        self.horizontalLayout_7.addWidget(self.drop_dropbutton)
        spacerItem9 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DDLDROP)
        QtCore.QMetaObject.connectSlotsByName(DDLDROP)

    def retranslateUi(self, DDLDROP):
        _translate = QtCore.QCoreApplication.translate
        DDLDROP.setWindowTitle(_translate("DDLDROP", "Drop"))
        self.label.setText(_translate("DDLDROP", "Database Name:"))
        self.drop_listtablebutton.setText(_translate("DDLDROP", "List All Tables"))
        self.label_3.setText(_translate("DDLDROP", "Table List"))
        self.label_2.setText(_translate("DDLDROP", "Table Name:"))
        self.drop_dropbutton.setText(_translate("DDLDROP", "DROP"))

