# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI_Files/DMLInsert.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DMLINSERT(object):
    def setupUi(self, DMLINSERT):
        DMLINSERT.setObjectName("DMLINSERT")
        DMLINSERT.resize(922, 610)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DMLINSERT)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(DMLINSERT)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.insert_dbname = QtWidgets.QTextEdit(DMLINSERT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_dbname.sizePolicy().hasHeightForWidth())
        self.insert_dbname.setSizePolicy(sizePolicy)
        self.insert_dbname.setObjectName("insert_dbname")
        self.horizontalLayout.addWidget(self.insert_dbname)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(DMLINSERT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(127, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.insert_dbtable = QtWidgets.QTextEdit(DMLINSERT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_dbtable.sizePolicy().hasHeightForWidth())
        self.insert_dbtable.setSizePolicy(sizePolicy)
        self.insert_dbtable.setObjectName("insert_dbtable")
        self.horizontalLayout_3.addWidget(self.insert_dbtable)
        spacerItem5 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.insert_selectbutton = QtWidgets.QPushButton(DMLINSERT)
        self.insert_selectbutton.setObjectName("insert_selectbutton")
        self.horizontalLayout_7.addWidget(self.insert_selectbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.insert_tableview = QtWidgets.QTableWidget(DMLINSERT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert_tableview.sizePolicy().hasHeightForWidth())
        self.insert_tableview.setSizePolicy(sizePolicy)
        self.insert_tableview.setObjectName("insert_tableview")
        self.insert_tableview.setColumnCount(0)
        self.insert_tableview.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.insert_tableview)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.insert_insertbutton = QtWidgets.QPushButton(DMLINSERT)
        self.insert_insertbutton.setObjectName("insert_insertbutton")
        self.horizontalLayout_5.addWidget(self.insert_insertbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DMLINSERT)
        QtCore.QMetaObject.connectSlotsByName(DMLINSERT)

    def retranslateUi(self, DMLINSERT):
        _translate = QtCore.QCoreApplication.translate
        DMLINSERT.setWindowTitle(_translate("DMLINSERT", "Insert"))
        self.label.setText(_translate("DMLINSERT", "Database Name:"))
        self.label_2.setText(_translate("DMLINSERT", "Table Name:"))
        self.insert_selectbutton.setText(_translate("DMLINSERT", "SELECT"))
        self.insert_insertbutton.setText(_translate("DMLINSERT", "INSERT"))

