# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI_Files/DMLUpdate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DMLUPDATE(object):
    def setupUi(self, DMLUPDATE):
        DMLUPDATE.setObjectName("DMLUPDATE")
        DMLUPDATE.resize(903, 622)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DMLUPDATE)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(DMLUPDATE)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.update_dbname = QtWidgets.QTextEdit(DMLUPDATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_dbname.sizePolicy().hasHeightForWidth())
        self.update_dbname.setSizePolicy(sizePolicy)
        self.update_dbname.setObjectName("update_dbname")
        self.horizontalLayout.addWidget(self.update_dbname)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(DMLUPDATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(127, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.update_dbtable = QtWidgets.QTextEdit(DMLUPDATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_dbtable.sizePolicy().hasHeightForWidth())
        self.update_dbtable.setSizePolicy(sizePolicy)
        self.update_dbtable.setObjectName("update_dbtable")
        self.horizontalLayout_3.addWidget(self.update_dbtable)
        spacerItem5 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.update_selectbutton = QtWidgets.QPushButton(DMLUPDATE)
        self.update_selectbutton.setObjectName("update_selectbutton")
        self.horizontalLayout_7.addWidget(self.update_selectbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.update_tableview = QtWidgets.QTableWidget(DMLUPDATE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_tableview.sizePolicy().hasHeightForWidth())
        self.update_tableview.setSizePolicy(sizePolicy)
        self.update_tableview.setObjectName("update_tableview")
        self.update_tableview.setColumnCount(0)
        self.update_tableview.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.update_tableview)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(700, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.update_updatebutton = QtWidgets.QPushButton(DMLUPDATE)
        self.update_updatebutton.setObjectName("update_updatebutton")
        self.horizontalLayout_5.addWidget(self.update_updatebutton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DMLUPDATE)
        QtCore.QMetaObject.connectSlotsByName(DMLUPDATE)

    def retranslateUi(self, DMLUPDATE):
        _translate = QtCore.QCoreApplication.translate
        DMLUPDATE.setWindowTitle(_translate("DMLUPDATE", "Update"))
        self.label.setText(_translate("DMLUPDATE", "Database Name:"))
        self.label_2.setText(_translate("DMLUPDATE", "Table Name:"))
        self.update_selectbutton.setText(_translate("DMLUPDATE", "SELECT"))
        self.update_updatebutton.setText(_translate("DMLUPDATE", "UPDATE"))

