# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI_Files/mdvisual.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1062, 839)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.deleteDB = QtWidgets.QPushButton(self.centralwidget)
        self.deleteDB.setObjectName("deleteDB")
        self.horizontalLayout.addWidget(self.deleteDB)
        self.connectDB = QtWidgets.QPushButton(self.centralwidget)
        self.connectDB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.connectDB.setAutoDefault(False)
        self.connectDB.setDefault(False)
        self.connectDB.setFlat(False)
        self.connectDB.setObjectName("connectDB")
        self.horizontalLayout.addWidget(self.connectDB)
        self.createDB = QtWidgets.QPushButton(self.centralwidget)
        self.createDB.setObjectName("createDB")
        self.horizontalLayout.addWidget(self.createDB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.in_query = QtWidgets.QTextEdit(self.centralwidget)
        self.in_query.setObjectName("in_query")
        self.verticalLayout_4.addWidget(self.in_query)
        self.runQuerytoDB = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runQuerytoDB.sizePolicy().hasHeightForWidth())
        self.runQuerytoDB.setSizePolicy(sizePolicy)
        self.runQuerytoDB.setObjectName("runQuerytoDB")
        self.verticalLayout_4.addWidget(self.runQuerytoDB)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.out_query = QtWidgets.QTextEdit(self.centralwidget)
        self.out_query.setObjectName("out_query")
        self.verticalLayout_3.addWidget(self.out_query)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.out_disp = QtWidgets.QTextEdit(self.centralwidget)
        self.out_disp.setObjectName("out_disp")
        self.verticalLayout_3.addWidget(self.out_disp)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.verticalLayout_3.addWidget(self.status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 26))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDML = QtWidgets.QMenu(self.menubar)
        self.menuDML.setObjectName("menuDML")
        self.menuDDL = QtWidgets.QMenu(self.menubar)
        self.menuDDL.setObjectName("menuDDL")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect_to_DB = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_DB.setObjectName("actionConnect_to_DB")
        self.actionCreate_DB = QtWidgets.QAction(MainWindow)
        self.actionCreate_DB.setObjectName("actionCreate_DB")
        self.actionDelete_DB = QtWidgets.QAction(MainWindow)
        self.actionDelete_DB.setObjectName("actionDelete_DB")
        self.actionAdd_New_DB = QtWidgets.QAction(MainWindow)
        self.actionAdd_New_DB.setObjectName("actionAdd_New_DB")
        self.actionInsert = QtWidgets.QAction(MainWindow)
        self.actionInsert.setObjectName("actionInsert")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionDrop = QtWidgets.QAction(MainWindow)
        self.actionDrop.setObjectName("actionDrop")
        self.actionAlter = QtWidgets.QAction(MainWindow)
        self.actionAlter.setObjectName("actionAlter")
        self.menuFile.addAction(self.actionConnect_to_DB)
        self.menuFile.addAction(self.actionCreate_DB)
        self.menuFile.addAction(self.actionDelete_DB)
        self.menuFile.addAction(self.actionAdd_New_DB)
        self.menuDML.addAction(self.actionInsert)
        self.menuDML.addAction(self.actionUpdate)
        self.menuDML.addAction(self.actionDelete)
        self.menuDDL.addAction(self.actionCreate)
        self.menuDDL.addAction(self.actionDrop)
        self.menuDDL.addAction(self.actionAlter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDML.menuAction())
        self.menubar.addAction(self.menuDDL.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MDVisual"))
        self.deleteDB.setText(_translate("MainWindow", "Delete Database"))
        self.connectDB.setText(_translate("MainWindow", "Connect"))
        self.createDB.setText(_translate("MainWindow", "Create Database"))
        self.label.setText(_translate("MainWindow", "Query"))
        self.runQuerytoDB.setText(_translate("MainWindow", "Run Query"))
        self.label_2.setText(_translate("MainWindow", "Output"))
        self.label_3.setText(_translate("MainWindow", "Display"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDML.setTitle(_translate("MainWindow", "DML"))
        self.menuDDL.setTitle(_translate("MainWindow", "DDL"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionConnect_to_DB.setText(_translate("MainWindow", "Connect to DB"))
        self.actionCreate_DB.setText(_translate("MainWindow", "Create DB"))
        self.actionDelete_DB.setText(_translate("MainWindow", "Delete DB"))
        self.actionAdd_New_DB.setText(_translate("MainWindow", "Add New DB"))
        self.actionInsert.setText(_translate("MainWindow", "Insert"))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionDrop.setText(_translate("MainWindow", "Drop"))
        self.actionAlter.setText(_translate("MainWindow", "Alter"))

